- alias: Indoor motion detected
  trigger:
    platform: state
    entity_id: binary_sensor.huiskamersensor_motion
    to: 'on'
  condition:
    - condition: state
      entity_id: light.huiskamer
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.indoor_motion_sensor_light_level
      below: 20
  action:
    - service: homeassistant.turn_on
      data_template:
        entity_id: light.keuken
        brightness: 102
    - service: homeassistant.turn_on
      data_template:
        entity_id: light.speelhoek
        brightness: 102
    - service: homeassistant.turn_on
      data_template:
        entity_id: light.aanbouw
        brightness: 102

- alias: Outdoor motion detected
  trigger:
    platform: state
    entity_id: binary_sensor.hue_outdoor_motion_sensor_1_motion
    to: 'on'
  condition:
    - condition: state
      entity_id: light.tuin
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.outdoor_motion_sensor_light_level
      below: 20
  action:
    - service: homeassistant.turn_on
      data_template:
        entity_id: light.tuin
        brightness: 255
    - service: input_text.set_value
      data_template:
        entity_id: input_text.outdoor_motion_automation_is_triggered
        value: 'true'

- alias: Outdoor motion undetected
  trigger:
    platform: state
    entity_id: binary_sensor.hue_outdoor_motion_sensor_1_motion
    to: 'off'
    for:
      minutes: 2
  condition:
    condition: state
    entity_id: input_text.outdoor_motion_automation_is_triggered
    state: 'true'
  action:
    - service: homeassistant.turn_off
      entity_id: light.tuin
    - service: input_text.set_value
      data_template:
        entity_id: input_text.outdoor_motion_automation_is_triggered
        value: 'false'
