# Automations
automation: !include_dir_merge_list automations

# Enable configuration section
config:

# Enable energy dashboard
energy:

# Frontend (theme) configuration
frontend: !include configuration/frontend.yaml

# Favorite icon configuration
favicon: !include configuration/favicon.yaml

# Enable history tracking
history:

# Home Assistant
homeassistant: !include configuration/home-assistant.yaml

# Recorder settings
recorder: !include configuration/recorder.yaml

# HTTP
http: !include configuration/http.yaml

# input variables
input_boolean: !include configuration/input-boolean.yaml
input_number: !include configuration/input-number.yaml
input_select: !include configuration/input-select.yaml
input_text: !include configuration/input-text.yaml

# Lovelace configuration
lovelace: !include configuration/lovelace.yaml

# Nest
nest: !include configuration/nest.yaml

# Scripts
script: !include_dir_merge_named scripts

# Groups
group: !include_dir_merge_named groups
light: !include groups/lights.yaml

# Sensors
binary_sensor: !include_dir_merge_list binary-sensors
sensor: !include_dir_merge_list sensors

# Switches
switch: !include_dir_merge_list switches

# Enable system health information
system_health:

# Utility meter
utility_meter: !include configuration/utility-meter.yaml

# Device tracker
device_tracker: !include configuration/device-tracker.yaml

# Persons
person: !include configuration/person.yaml

# Rest commands
rest_command: !include configuration/rest-commands.yaml

# Text-to-Speech
tts: !include configuration/tts.yaml

# Enable Wake on LAN
wake_on_lan:
