# Automations
automation:
  - !include automations/motion-indoor-detected.yaml
  - !include automations/motion-outdoor-detected.yaml
  - !include automations/motion-outdoor-undetected.yaml

# Cloudflare
cloudflare: !include configuration/cloudflare.yaml

# Enable configuration section
config:

# Frontend (theme) configuration
frontend: !include configuration/frontend.yaml

# Favorite icon configuration
favicon: !include configuration/favicon.yaml

# Enable history tracking
history:

# Home Assistant
homeassistant: !include configuration/home-assistant.yaml

# HTTP
http: !include configuration/http.yaml

# Hue
hue: !include configuration/hue.yaml

# Automation variables
input_text: !include configuration/input-text.yaml

# Lovelace configuration
lovelace: !include configuration/lovelace.yaml

# Scripts
script: !include scripts/hue-scenes.yaml

# Sensors
binary_sensor:
  - !include sensors/hue-scenes.yaml
sensor:
  - !include sensors/baby-monitor.yaml
  - !include sensors/energy-monitors.yaml
  - !include sensors/motion-sensors.yaml
  - !include sensors/smart-meter.yaml
  - !include sensors/system-temperature.yaml
  - !include sensors/system-usage.yaml
  - !include sensors/utility-sensors.yaml

# Enable system health information
system_health:

# TP-Link
tplink: !include configuration/tp-link.yaml

# Utility Meter
utility_meter: !include configuration/utility-meter.yaml
