# Default config
default_config:

# HTTP
http:
#  base_url: !secret cloudflare_base_url
#  ssl_certificate: !secret cloudflare_ssl_cert
#  ssl_key: !secret cloudflare_ssl_key
  ip_ban_enabled: true
  login_attempts_threshold: 3

# Cloudflare
#cloudflare:
#  email: !secret cloudflare_email_address
#  api_key: !secret cloudflare_api_key
#  zone: !secret cloudflare_zone
#  records:
#    - !secret cloudflare_record

# UI mode
lovelace:
  mode: yaml

# TP-Link
tplink:
  switch:
    # Energy monitor (HS110)
    - host: !secret ip_tplink_hs110

# Includes
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
