# Default config
default_config:

# HTTP
http:
    ip_ban_enabled: true
    login_attempts_threshold: 5

# UI mode
lovelace:
  mode: yaml

# TP-Link
tplink:
  switch:
    # Energy monitor (HS110)
    # - host: 192.168.1.#

# Includes
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
