# System monitor
- platform: systemmonitor
  resources:
    - type: processor_use
    - type: memory_use_percent
    - type: disk_use_percent
      arg: /

# Smart meter
#- platform: dsmr
#  port: /dev/ttyUSB1
#  dsmr_version: 5

# Energy monitor (TP-Link HS110)
- platform: template
  sensors:
    energy_monitor_amps:
      friendly_name_template: "{{ states.switch.energy_monitor.name}} Stroomsterkte"
      value_template: '{{ states.switch.energy_monitor.attributes["current_a"] | float }}'
      unit_of_measurement: 'A'
    energy_monitor_watts:
      friendly_name_template: "{{ states.switch.energy_monitor.name}} Huidig verbruik"
      value_template: '{{ states.switch.energy_monitor.attributes["current_power_w"] | float }}'
      unit_of_measurement: 'W'
    energy_monitor_total_kwh:
      friendly_name_template: "{{ states.switch.energy_monitor.name}} Totaal verbruik"
      value_template: '{{ states.switch.energy_monitor.attributes["total_energy_kwh"] | float }}'
      unit_of_measurement: 'kWh'
    energy_monitor_volts:
      friendly_name_template: "{{ states.switch.energy_monitor.name}} Spanning"
      value_template: '{{ states.switch.energy_monitor.attributes["voltage"] | float }}'
      unit_of_measurement: 'V'
    energy_monitor_today_kwh:
      friendly_name_template: "{{ states.switch.energy_monitor.name}} Verbruik vandaag"
      value_template: '{{ states.switch.energy_monitor.attributes["today_energy_kwh"] | float }}'
      unit_of_measurement: 'kWh'
