# System monitor
- platform: systemmonitor
  resources:
    - type: processor_use
    - type: memory_use_percent
    - type: disk_use_percent
      arg: /

# System temperature
- platform: command_line
  name: Processor temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "째C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'

# Smart meter
#- platform: dsmr
#  port: /dev/ttyUSB1
#  dsmr_version: 5

# Energy monitor (TP-Link HS110)
- platform: template
  sensors:
    energy_monitor_1_watts:
      friendly_name_template: "{{ states.switch.energy_monitor.name }} Huidig verbruik"
      value_template: '{{ state_attr("switch.energy_monitor", "current_power_w") | float }}'
      unit_of_measurement: 'W'
    energy_monitor_1_today_kwh:
      friendly_name_template: "{{ states.switch.energy_monitor.name }} Verbruik vandaag"
      value_template: '{{ state_attr("switch.energy_monitor", "today_energy_kwh") | float }}'
      unit_of_measurement: 'kWh'
    energy_monitor_1_total_kwh:
      friendly_name_template: "{{ states.switch.energy_monitor.name }} Totaal verbruik"
      value_template: '{{ state_attr("switch.energy_monitor", "total_energy_kwh") | float }}'
      unit_of_measurement: 'kWh'

# Baby Monitor (Motorola MBP-854 Connect)
- platform: rest
  resource: !secret address_motorola_mbp854connect
  force_update: true
  name: Baby Monitor Temperature
  value_template: '{{ (value.split(": ")[1] | float) | round(1) }}'
  unit_of_measurement: "째C"

# Indoor motion sensor (Philips Hue SML001)
- platform: template
  sensors:
    indoor_motion_sensor_temperature:
      friendly_name: "Indoor Motion Sensor Temperature"
      unit_of_measurement: '째C'
      value_template: "{{ (states('sensor.huiskamersensor_temperature') | float) | round(1) }}"

# Outdoor motion sensor (Philips Hue SML002)
- platform: template
  sensors:
    outdoor_motion_sensor_temperature:
      friendly_name: "Outdoor Motion Sensor Temperature"
      unit_of_measurement: '째C'
      value_template: "{{ (states('sensor.hue_outdoor_motion_sensor_1_temperature') | float) | round(1) }}"
