# System monitor
- platform: systemmonitor
  resources:
    - type: processor_use
    - type: memory_use_percent
    - type: disk_use_percent
      arg: /

# System temperature
- platform: command_line
  name: Processor temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "째C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'

# Smart meter (Landis+Gyr E360)
- platform: dsmr
  port: /dev/ttyUSB0
  dsmr_version: 5
- platform: template
  sensors:
    daily_power:
      friendly_name: Daily Power
      unit_of_measurement: kWh
      value_template: "{{ (states('sensor.daily_power_offpeak') | float + states('sensor.daily_power_peak') | float) | round(3) }}"
    monthly_power:
      friendly_name: Monthly Power
      unit_of_measurement: kWh
      value_template: "{{ (states('sensor.monthly_power_offpeak') | float + states('sensor.monthly_power_peak') | float) | round(0) }}"
    total_power:
      friendly_name: Total Power
      unit_of_measurement: kWh
      value_template: "{{ (states('sensor.power_consumption_low') | float + states('sensor.power_consumption_normal') | float) | round(0) }}"
    monthly_gas_rounded:
      friendly_name: Monthly Gas (rounded)
      unit_of_measurement: m3
      value_template: "{{ states('sensor.monthly_gas') | float | round(0) }}"
    total_gas_rounded:
      friendly_name: Monthly Gas (rounded)
      unit_of_measurement: m3
      value_template: "{{ states('sensor.gas_consumption') | float | round(0) }}"

# Energy monitors (TP-Link HS110)
- platform: template
  sensors:
    energy_monitor_1_watts:
      friendly_name_template: "{{ states.switch.energy_monitor_1.name }} Huidig verbruik"
      value_template: '{{ state_attr("switch.energy_monitor_1", "current_power_w") | float }}'
      unit_of_measurement: 'W'
    energy_monitor_1_today_kwh:
      friendly_name_template: "{{ states.switch.energy_monitor_1.name }} Verbruik vandaag"
      value_template: '{{ state_attr("switch.energy_monitor_1", "today_energy_kwh") | float }}'
      unit_of_measurement: 'kWh'
    energy_monitor_1_total_kwh:
      friendly_name_template: "{{ states.switch.energy_monitor_1.name }} Totaal verbruik"
      value_template: '{{ state_attr("switch.energy_monitor_1", "total_energy_kwh") | float }}'
      unit_of_measurement: 'kWh'
    energy_monitor_2_watts:
      friendly_name_template: "{{ states.switch.energy_monitor_2.name }} Huidig verbruik"
      value_template: '{{ state_attr("switch.energy_monitor_2", "current_power_w") | float }}'
      unit_of_measurement: 'W'
    energy_monitor_2_today_kwh:
      friendly_name_template: "{{ states.switch.energy_monitor_2.name }} Verbruik vandaag"
      value_template: '{{ state_attr("switch.energy_monitor_2", "today_energy_kwh") | float }}'
      unit_of_measurement: 'kWh'
    energy_monitor_2_total_kwh:
      friendly_name_template: "{{ states.switch.energy_monitor_2.name }} Totaal verbruik"
      value_template: '{{ state_attr("switch.energy_monitor_2", "total_energy_kwh") | float }}'
      unit_of_measurement: 'kWh'
    energy_monitor_3_watts:
      friendly_name_template: "{{ states.switch.energy_monitor_3.name }} Huidig verbruik"
      value_template: '{{ state_attr("switch.energy_monitor_3", "current_power_w") | float }}'
      unit_of_measurement: 'W'
    energy_monitor_3_today_kwh:
      friendly_name_template: "{{ states.switch.energy_monitor_3.name }} Verbruik vandaag"
      value_template: '{{ state_attr("switch.energy_monitor_3", "today_energy_kwh") | float }}'
      unit_of_measurement: 'kWh'
    energy_monitor_3_total_kwh:
      friendly_name_template: "{{ states.switch.energy_monitor_3.name }} Totaal verbruik"
      value_template: '{{ state_attr("switch.energy_monitor_3", "total_energy_kwh") | float }}'
      unit_of_measurement: 'kWh'

# Baby Monitor (Motorola MBP-854 Connect)
- platform: rest
  resource: !secret address_motorola_mbp854connect
  force_update: true
  name: Baby Monitor Temperature
  value_template: '{{ (value.split(": ")[1] | float) | round(1) }}'
  unit_of_measurement: "째C"

# Indoor motion sensor (Philips Hue SML001)
- platform: template
  sensors:
    indoor_motion_sensor_temperature:
      friendly_name: "Indoor Motion Sensor Temperature"
      unit_of_measurement: '째C'
      value_template: "{{ (states('sensor.huiskamersensor_temperature') | float) | round(1) }}"
    indoor_motion_sensor_light_level:
      friendly_name: "Indoor Motion Sensor Light Level"
      unit_of_measurement: 'lx'
      value_template: "{{ (states('sensor.huiskamersensor_light_level') | float) | round(0) }}"

# Outdoor motion sensor (Philips Hue SML002)
- platform: template
  sensors:
    outdoor_motion_sensor_temperature:
      friendly_name: "Outdoor Motion Sensor Temperature"
      unit_of_measurement: '째C'
      value_template: "{{ (states('sensor.hue_outdoor_motion_sensor_1_temperature') | float) | round(1) }}"
    outdoor_motion_sensor_light_level:
      friendly_name: "Outdoor Motion Sensor Light Level"
      unit_of_measurement: 'lx'
      value_template: "{{ (states('sensor.hue_outdoor_motion_sensor_1_light_level') | float) | round(0) }}"
