# Application title
title: Thuis

# Custom Header configuration
custom_header: !include lovelace/configuration/header.yaml

# Swipe Navigation configuration
swipe_nav: !include lovelace/configuration/swipe.yaml

# Views
views:
  - !include lovelace/views/home.yaml
  - !include lovelace/views/lighting.yaml
  - !include lovelace/views/media.yaml
  - !include lovelace/views/climate.yaml
  - !include lovelace/views/energy.yaml
  - !include lovelace/views/motion.yaml
  - !include lovelace/views/system.yaml
