# Compact Custom Header
resources:
  - url: /local/custom-lovelace/compact-custom-header/compact-custom-header.js?v=1.3.5
    type: module
cch:
  disable_sidebar: true
  menu: hide
  options: hide
  swipe: true
  swipe_animate: swipe
  swipe_prevent_default: true
  exceptions:
  - conditions:
      user: Administrator
    config:
      disable_sidebar: false
      menu: show
      options: show

# Views
title: Thuis
views:
  - title: Home
    path: home
    icon: mdi:home-variant-outline
    cards:
      - type: entities
        title: Verlichting
        entities:
          - entity: light.keuken
            icon: mdi:stove
          - entity: light.eettafel
            name: Eettafel
            icon: mdi:ceiling-light
          - entity: light.speelhoek
            name: Speelhoek
            icon: mdi:castle
          - entity: light.aanbouw
            name: Aanbouw
            icon: mdi:track-light
          - entity: light.vloerlamp_2
            name: Vloerlamp
            icon: mdi:floor-lamp
      - type: entities
        title: Temperatuur
        show_header_toggle: false
        entities:
          - entity: sensor.indoor_motion_sensor_temperature
            name: Huiskamer
          - entity: sensor.baby_monitor_temperature
            name: Kinderkamer
  - title: Verlichting
    path: lighting
    icon: mdi:lightbulb-outline
    cards:
      - type: glance
        title: Scenes
        show_state: false
        columns: 3
        entities:
          - entity: script.hue_scene_overdag
            name: Overdag
            icon: mdi:weather-sunny
            tap_action:
              action: call-service
              service: script.hue_scene_overdag
          - entity: script.hue_scene_eten
            name: Eten
            icon: mdi:silverware-fork-knife
            tap_action:
              action: call-service
              service: script.hue_scene_eten
          - entity: script.hue_scene_tvkijken
            name: TV Kijken
            icon: mdi:sofa
            tap_action:
              action: call-service
              service: script.hue_scene_tvkijken
          - entity: script.hue_scene_avond
            name: Avond
            icon: mdi:weather-night
            tap_action:
              action: call-service
              service: script.hue_scene_avond
          - entity: script.hue_scene_koken
            name: Koken
            icon: mdi:stove
            tap_action:
              action: call-service
              service: script.hue_scene_koken
          - entity: script.hue_scene_spelen
            name: Spelen
            icon: mdi:castle
            tap_action:
              action: call-service
              service: script.hue_scene_spelen
  - title: Verbruik
    path: usage
    icon: mdi:flash-outline
    cards:
      - type: entities
        entities:
          - entity: switch.energy_monitor
            name: Energy monitor
            icon: mdi:flash
          - entity: sensor.energy_monitor_watts
            name: Huidig verbruik
            icon: mdi:gauge
          - entity: sensor.energy_monitor_today_kwh
            name: Verbruik vandaag
            icon: mdi:gauge
          - entity: sensor.energy_monitor_total_kwh
            name: Totaal verbruik
            icon: mdi:gauge
  - title: Klimaat
    path: climate
    icon: mdi:thermometer
    cards:
      - type: sensor
        entity: sensor.indoor_motion_sensor_temperature
        graph: line
        name: Huiskamer
      - type: sensor
        entity: sensor.baby_monitor_temperature
        graph: line
        name: Kinderkamer
  - title: Systeem
    path: system
    icon: mdi:settings-outline
    cards:
      - type: gauge
        name: Processor
        entity: sensor.processor_use
      - type: gauge
        name: Geheugen
        entity: sensor.memory_use_percent
      - type: gauge
        name: Schijfruimte
        entity: sensor.disk_use_percent
