title: Thuis
views:
  - path: lighting
    title: Verlichting
    cards:
      - type: entities
        entities:
          - entity: light.eettafel
            name: Eettafel
            icon: mdi:ceiling-light
  - path: energy
    title: Verbruik
    cards:
      - type: entities
        entities:
          - entity: switch.energy_monitor
            name: Energy monitor
            icon: mdi:flash
