title: Thuis
views:
  - path: lighting
    title: Verlichting
    cards:
      - type: entities
        title: Huiskamer
        entities:
          - entity: light.keuken
            icon: mdi:stove
          - entity: light.eettafel
            name: Eettafel
            icon: mdi:ceiling-light
          - entity: light.speelhoek
            name: Speelhoek
            icon: mdi:castle
          - entity: light.aanbouw
            name: Aanbouw
            icon: mdi:track-light
          - entity: light.vloerlamp
            name: Vloerlamp
            icon: mdi:floor-lamp
      - type: glance
        title: Scenes
        show_state: false
        columns: 3
        entities:
          - entity: script.hue_scene_overdag
            name: Overdag
            icon: mdi:weather-sunny
            tap_action:
              action: call-service
              service: script.hue_scene_overdag
          - entity: script.hue_scene_eten
            name: Eten
            icon: mdi:silverware-fork-knife
            tap_action:
              action: call-service
              service: script.hue_scene_eten
          - entity: script.hue_scene_tvkijken
            name: TV Kijken
            icon: mdi:sofa
            tap_action:
              action: call-service
              service: script.hue_scene_tvkijken
          - entity: script.hue_scene_avond
            name: Avond
            icon: mdi:weather-night
            tap_action:
              action: call-service
              service: script.hue_scene_avond
          - entity: script.hue_scene_koken
            name: Koken
            icon: mdi:stove
            tap_action:
              action: call-service
              service: script.hue_scene_koken
          - entity: script.hue_scene_spelen
            name: Spelen
            icon: mdi:castle
            tap_action:
              action: call-service
              service: script.hue_scene_spelen
  - path: energy
    title: Verbruik
    cards:
      - type: entities
        entities:
          - entity: switch.energy_monitor
            name: Energy monitor
            icon: mdi:flash
