# Application title
title: Thuis

# Import resources
resources: !include lovelace/configuration/resources.yaml

# Custom Header configuration
custom_header: !include lovelace/configuration/header.yaml

# Views
views:
  - !include lovelace/views/home.yaml
  - !include lovelace/views/lighting.yaml
  - !include lovelace/views/motion.yaml
  - !include lovelace/views/usage.yaml
  - !include lovelace/views/climate.yaml
  - !include lovelace/views/system.yaml
