# Import resources
resources:
  # Card Mod
  - url: /local/custom-lovelace/card-mod.js?v=5
    type: module
  # Compact Custom Header
  - url: /local/custom-lovelace/compact-custom-header.js?v=1.3.5
    type: module
  # Mini Graph Card
  - url: /local/custom-lovelace/mini-graph-card-bundle.js?v=0.6.0
    type: module
  # Slider Entity Row
  - url: /local/custom-lovelace/slider-entity-row.js?v=7
    type: module

# Compact Custom Header Configuration
cch:
  disable_sidebar: true
  menu: hide
  options: hide
  swipe: true
  swipe_animate: swipe
  swipe_prevent_default: true
  exceptions:
  - conditions:
      user: Administrator
    config:
      disable_sidebar: false
      menu: show
      options: show

# Views
title: Thuis
views:
  # Home view
  - title: Home
    path: home
    icon: mdi:home-variant-outline
    cards:
      - type: vertical-stack
        cards:
          - type: entities
            style: |
              ha-card {
                margin: 3px 6px
              }
              @media screen and (max-width: 500px) { 
                ha-card {
                  margin: 3px 14px
                }
              }
            title: Huiskamer
            entities:
              - type: custom:slider-entity-row
                entity: light.keuken
                icon: mdi:stove
                toggle: true
                hide_when_off: true
              - type: custom:slider-entity-row
                entity: light.eettafel
                icon: mdi:ceiling-light
                toggle: true
                hide_when_off: true
              - type: custom:slider-entity-row
                entity: light.speelhoek
                icon: mdi:castle
                toggle: true
                hide_when_off: true
              - type: custom:slider-entity-row
                entity: light.aanbouw
                icon: mdi:track-light
                toggle: true
                hide_when_off: true
              - type: custom:slider-entity-row
                entity: light.vloerlamp_2
                icon: mdi:floor-lamp
                toggle: true
                hide_when_off: true
              - type: divider
                style:
                  height: 1px
                  margin-left: 55px
                  background-color: "#333333"
              - entity: sensor.indoor_motion_sensor_temperature
                name: Temperatuur
              - entity: sensor.indoor_motion_sensor_light_level
                name: Verlichtingssterkte
          - type: entities
            style: |
              ha-card {
                margin: 3px 6px
              }
              @media screen and (max-width: 500px) { 
                ha-card {
                  margin: 3px 14px
                }
              }
            title: Kinderkamer
            show_header_toggle: false
            entities:
              - entity: sensor.baby_monitor_temperature
                name: Temperatuur
          - type: entities
            style: |
              ha-card {
                margin: 3px 6px
              }
              @media screen and (max-width: 500px) { 
                ha-card {
                  margin: 3px 14px
                }
              }
            title: Tuin
            entities:
              - type: custom:slider-entity-row
                entity: light.deurlamp
                icon: mdi:outdoor-lamp
                toggle: true
                hide_when_off: true
              - type: custom:slider-entity-row
                entity: light.schuurlamp
                icon: mdi:outdoor-lamp
                toggle: true
                hide_when_off: true
              - type: divider
                style:
                  height: 1px
                  margin-left: 55px
                  background-color: "#333333"
              - entity: sensor.outdoor_motion_sensor_temperature
                name: Temperatuur
              - entity: sensor.outdoor_motion_sensor_light_level
                name: Verlichtingssterkte
  # Lighting view
  - title: Verlichting
    path: lighting
    icon: mdi:lightbulb-outline
    cards:
      - type: vertical-stack
        cards:
          - type: glance
            style: |
              ha-card {
                margin: 3px 6px
              }
              @media screen and (max-width: 500px) { 
                ha-card {
                  margin: 3px 14px
                }
              }
            title: Scenes
            show_state: false
            columns: 3
            entities:
              - entity: script.hue_scene_overdag
                name: Overdag
                icon: mdi:weather-sunny
                tap_action:
                  action: call-service
                  service: script.hue_scene_overdag
              - entity: script.hue_scene_eten
                name: Eten
                icon: mdi:silverware-fork-knife
                tap_action:
                  action: call-service
                  service: script.hue_scene_eten
              - entity: script.hue_scene_tvkijken
                name: TV Kijken
                icon: mdi:sofa
                tap_action:
                  action: call-service
                  service: script.hue_scene_tvkijken
              - entity: script.hue_scene_avond
                name: Avond
                icon: mdi:weather-night
                tap_action:
                  action: call-service
                  service: script.hue_scene_avond
              - entity: script.hue_scene_koken
                name: Koken
                icon: mdi:stove
                tap_action:
                  action: call-service
                  service: script.hue_scene_koken
              - entity: script.hue_scene_spelen
                name: Spelen
                icon: mdi:castle
                tap_action:
                  action: call-service
                  service: script.hue_scene_spelen
          - type: glance
            style: |
              ha-card {
                margin: 3px 6px
              }
              @media screen and (max-width: 500px) { 
                ha-card {
                  margin: 3px 14px
                }
              }
            title: Huiskamer
            show_state: false
            columns: 3
            entities:
              - entity: light.keuken
                icon: mdi:stove
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
              - entity: light.eettafel
                icon: mdi:ceiling-light
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
              - entity: light.speelhoek
                icon: mdi:castle
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
              - entity: light.aanbouw
                icon: mdi:track-light
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
              - entity: light.vloerlamp_2
                icon: mdi:floor-lamp
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
          - type: glance
            style: |
              ha-card {
                margin: 3px 6px
              }
              @media screen and (max-width: 500px) { 
                ha-card {
                  margin: 3px 14px
                }
              }
            title: Tuin
            show_state: false
            columns: 2
            entities:
              - entity: light.deurlamp
                icon: mdi:outdoor-lamp
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
              - entity: light.schuurlamp
                icon: mdi:outdoor-lamp
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
  # Usage view
  - title: Verbruik
    path: usage
    icon: mdi:flash-outline
    cards:
      - type: vertical-stack
        cards:
          - type: conditional
            conditions:
              - entity: switch.energy_monitor_1
                state: "on"
            card:
              type: entities
              style: |
                ha-card {
                  margin: 3px 6px
                }
                @media screen and (max-width: 500px) { 
                  ha-card {
                    margin: 3px 14px
                  }
                }
              title: Energiemeter 1
              show_header_toggle: false
              entities:
                - entity: sensor.energy_monitor_1_watts
                  name: Huidig verbruik
                  icon: mdi:flash-outline
                - entity: sensor.energy_monitor_1_today_kwh
                  name: Verbruik vandaag
                  icon: mdi:gauge
                - entity: sensor.energy_monitor_1_total_kwh
                  name: Totaal verbruik
                  icon: mdi:gauge
          - type: conditional
            conditions:
              - entity: switch.energy_monitor_2
                state: "on"
            card:
              type: entities
              style: |
                ha-card {
                  margin: 3px 6px
                }
                @media screen and (max-width: 500px) { 
                  ha-card {
                    margin: 3px 14px
                  }
                }
              title: Energiemeter 2
              show_header_toggle: false
              entities:
                - entity: sensor.energy_monitor_2_watts
                  name: Huidig verbruik
                  icon: mdi:flash-outline
                - entity: sensor.energy_monitor_2_today_kwh
                  name: Verbruik vandaag
                  icon: mdi:gauge
                - entity: sensor.energy_monitor_2_total_kwh
                  name: Totaal verbruik
                  icon: mdi:gauge
          - type: conditional
            conditions:
              - entity: switch.energy_monitor_3
                state: "on"
            card:
              type: entities
              style: |
                ha-card {
                  margin: 3px 6px
                }
                @media screen and (max-width: 500px) { 
                  ha-card {
                    margin: 3px 14px
                  }
                }
              title: Energiemeter 3
              show_header_toggle: false
              entities:
                - entity: sensor.energy_monitor_3_watts
                  name: Huidig verbruik
                  icon: mdi:flash-outline
                - entity: sensor.energy_monitor_3_today_kwh
                  name: Verbruik vandaag
                  icon: mdi:gauge
                - entity: sensor.energy_monitor_3_total_kwh
                  name: Totaal verbruik
                  icon: mdi:gauge
          - type: conditional
            conditions:
              - entity: switch.energy_monitor_1
                state_not: "on"
              - entity: switch.energy_monitor_2
                state_not: "on"
              - entity: switch.energy_monitor_3
                state_not: "on"
            card:
              type: markdown
              style: |
                ha-card {
                  margin: 3px 6px
                }
                @media screen and (max-width: 500px) { 
                  ha-card {
                    margin: 3px 14px
                  }
                }
              title: Geen actieve energiemeters
              content: >
                Op dit moment zijn er geen energiemeters actief
  # Climate view
  - title: Klimaat
    path: climate
    icon: mdi:thermometer
    cards:
      - type: vertical-stack
        cards:
          - type: sensor
            style: |
              ha-card {
                margin: 3px 6px
              }
              @media screen and (max-width: 500px) { 
                ha-card {
                  margin: 3px 14px
                }
              }
            entity: sensor.indoor_motion_sensor_temperature
            name: Huiskamer
            graph: line
            detail: 2
          - type: sensor
            style: |
              ha-card {
                margin: 3px 6px
              }
              @media screen and (max-width: 500px) { 
                ha-card {
                  margin: 3px 14px
                }
              }
            entity: sensor.baby_monitor_temperature
            name: Kinderkamer
            graph: line
            detail: 2
          - type: sensor
            style: |
              ha-card {
                margin: 3px 6px
              }
              @media screen and (max-width: 500px) { 
                ha-card {
                  margin: 3px 14px
                }
              }
            entity: sensor.outdoor_motion_sensor_temperature
            name: Tuin
            graph: line
            detail: 2
  # System view
  - title: Systeem
    path: system
    icon: mdi:server-network
    cards:
      - type: vertical-stack
        cards:
          - type: custom:mini-graph-card
            style: |
              ha-card {
                margin: 3px 6px
              }
              .name,
              .name > span {
                font-size: 24px !important;
                opacity: 1 !important;
              }
              .states {
                font-size: 10px;
              }
              @media screen and (max-width: 500px) { 
                ha-card {
                  margin: 3px 14px
                }
              }
            name: Temperatuur
            entities:
             - sensor.processor_temperature
            show:
              labels: true
              points: false
            points_per_hour: 30
            line_width: 1
            line_color: "#ff8906"
          - type: custom:mini-graph-card
            style: |
              ha-card {
                margin: 3px 6px
              }
              .name,
              .name > span {
                font-size: 24px !important;
                opacity: 1 !important;
              }
              .states {
                font-size: 10px;
              }
              @media screen and (max-width: 500px) { 
                ha-card {
                  margin: 3px 14px
                }
              }
            name: Verbruik
            entities:
              - entity: sensor.processor_use
                name: Processor
                show_fill: false
              - entity: sensor.memory_use_percent
                name: Geheugen
                show_fill: false
              - entity: sensor.disk_use_percent
                name: Harde schijf
                show_fill: false
            show:
              labels: true
              points: false
              state: false
            points_per_hour: 30
            line_width: 1
            line_color:
              - "#e63535"
              - "#337fbf"
              - "#7bcc00"
