- platform: group
  name: Beneden
  entities:
    - light.toilet
    - light.spots
    - light.keuken_1
    - light.keuken_2
    - light.eettafel_1
    - light.eettafel_2
    - light.twinkly_strings
    - light.speelhoek_1
    - light.speelhoek_2
    - light.aanbouw_1
    - light.aanbouw_2
    - light.tv
    - light.vloerlamp
- platform: group
  name: Huiskamer
  entities:
    - light.spots
    - light.keuken_1
    - light.keuken_2
    - light.eettafel_1
    - light.eettafel_2
    - light.twinkly_strings
    - light.speelhoek_1
    - light.speelhoek_2
    - light.aanbouw_1
    - light.aanbouw_2
    - light.tv
    - light.vloerlamp
- platform: group
  name: Keuken
  entities:
    - light.keuken_1
    - light.keuken_2
- platform: group
  name: Eettafel
  entities:
    - light.eettafel_1
    - light.eettafel_2
- platform: group
  name: Speelhoek
  entities:
    - light.speelhoek_1
    - light.speelhoek_2
- platform: group
  name: Aanbouw
  entities:
    - light.aanbouw_1
    - light.aanbouw_2
- platform: group
  name: Kerstverlichting
  entities:
    - light.twinkly_strings
    - light.twinkly_icicle
- platform: group
  name: Buiten
  entities:
    - light.voordeur
    - light.achterdeur
    - light.twinkly_icicle
    - light.schuur
    - light.parkeerplaats
- platform: group
  name: Boven
  entities:
    - light.overloop
    - light.kinderkamer
    - light.slaapkamer
    - light.bureau
