# Hue scenes
- platform: template
  sensors:
    hue_scene_huiskamer_overdag:
      device_class: light
      value_template: >-
        {{  is_state('light.keuken', 'on')
            and is_state_attr('light.keuken', 'brightness', 204)
            and is_state('light.eettafel', 'on')
            and is_state_attr('light.eettafel', 'brightness', 204)
            and is_state('light.speelhoek', 'on')
            and is_state_attr('light.speelhoek', 'brightness', 204)
            and is_state('light.aanbouw', 'on')
            and is_state_attr('light.aanbouw', 'brightness', 204)
            and is_state('light.vloerlamp', 'off')
        }}
    hue_scene_huiskamer_avond:
      device_class: light
      value_template: >-
        {{  is_state('light.keuken', 'on')
            and is_state_attr('light.keuken', 'brightness', 179)
            and is_state('light.eettafel', 'on')
            and is_state_attr('light.eettafel', 'brightness', 179)
            and is_state('light.speelhoek', 'on')
            and is_state_attr('light.speelhoek', 'brightness', 179)
            and is_state('light.aanbouw', 'on')
            and is_state_attr('light.aanbouw', 'brightness', 179)
            and is_state('light.vloerlamp', 'off')
        }}
    hue_scene_huiskamer_eten:
      device_class: light
      value_template: >-
        {{  is_state('light.keuken', 'off')
            and is_state('light.eettafel', 'on')
            and is_state_attr('light.eettafel', 'brightness', 217)
            and is_state('light.speelhoek', 'off')
            and is_state('light.aanbouw', 'off')
            and is_state('light.vloerlamp', 'off')
        }}
    hue_scene_huiskamer_koken:
      device_class: light
      value_template: >-
        {{  is_state('light.keuken', 'on')
            and is_state_attr('light.keuken', 'brightness', 254)
            and is_state('light.eettafel', 'on')
            and is_state_attr('light.eettafel', 'brightness', 128)
            and is_state('light.speelhoek', 'off')
            and is_state('light.aanbouw', 'off')
            and is_state('light.vloerlamp', 'off')
        }}
    hue_scene_huiskamer_tvkijken:
      device_class: light
      value_template: >-
        {{  is_state('light.keuken', 'off')
            and is_state('light.eettafel', 'on')
            and is_state_attr('light.eettafel', 'brightness', 166)
            and is_state_attr('light.eettafel', 'hs_color', (37.975,30.98))
            and is_state_attr('light.eettafel', 'rgb_color', (255,226,176))
            and is_state_attr('light.eettafel', 'xy_color', (0.397,0.378))
            and is_state('light.speelhoek', 'off')
            and is_state('light.aanbouw', 'off')
            and is_state('light.vloerlamp', 'on')
            and is_state_attr('light.vloerlamp', 'brightness', 166)
            and is_state_attr('light.vloerlamp', 'hs_color', (37.975,30.98))
            and is_state_attr('light.vloerlamp', 'rgb_color', (255,226,176))
            and is_state_attr('light.vloerlamp', 'xy_color', (0.397,0.378))
        }}
    hue_scene_huiskamer_spelen:
      device_class: light
      value_template: >-
        {{  is_state('light.keuken', 'on')
            and is_state_attr('light.keuken', 'brightness', 102)
            and is_state('light.eettafel', 'on')
            and is_state_attr('light.eettafel', 'brightness', 153)
            and is_state('light.speelhoek', 'on')
            and is_state_attr('light.speelhoek', 'brightness', 204)
            and is_state('light.aanbouw', 'on')
            and is_state_attr('light.aanbouw', 'brightness', 153)
            and is_state('light.vloerlamp', 'off')
        }}
