# Motion sensors (Philips Hue SML001, Philips Hue SML002)
- platform: template
  sensors:
    # Sensor 11
    hue_motion_sensor_1_motion_api:
      device_class: motion
      value_template: >-
        {{ states('sensor.hue_motion_sensor_api').split(',')[0].split('=')[1]}}
    # Sensor 21
    hue_motion_sensor_2_motion_api:
      device_class: motion
      value_template: >-
        {{ states('sensor.hue_motion_sensor_api').split(',')[2].split('=')[1]}}
    # Sensor 14
    hue_outdoor_motion_sensor_1_motion_api:
      device_class: motion
      value_template: >-
        {{ states('sensor.hue_motion_sensor_api').split(',')[1].split('=')[1]}}
    # Sensor 25
    hue_outdoor_motion_sensor_2_motion_api:
      device_class: motion
      value_template: >-
        {{ states('sensor.hue_motion_sensor_api').split(',')[3].split('=')[1]}}
