# Motion sensors (Philips Hue SML001, Philips Hue SML002)
- platform: template
  sensors:
    # Sensor 11
    motion_sensor_huiskamer_1_motion_api:
      device_class: motion
      value_template: >-
        {{ states('sensor.motion_sensor_api').split(',')[0].split('=')[1]}}
    # Sensor 21
    motion_sensor_huiskamer_2_motion_api:
      device_class: motion
      value_template: >-
        {{ states('sensor.motion_sensor_api').split(',')[2].split('=')[1]}}
    # Sensor 14
    motion_sensor_tuin_1_motion_api:
      device_class: motion
      value_template: >-
        {{ states('sensor.motion_sensor_api').split(',')[1].split('=')[1]}}
    # Sensor 25
    motion_sensor_parkeerplaats_motion_api:
      device_class: motion
      value_template: >-
        {{ states('sensor.motion_sensor_api').split(',')[3].split('=')[1]}}
