# Button sensors (Philips Hue ROM001)
- platform: template
  sensors:
    # Sensor 56
    button_1_update_api:
      value_template: >-
        {{ states('sensor.hue_sensor_api').split(',')[10].split('=')[1]}}
    button_1_state_api:
      value_template: >-
        {{ states('sensor.hue_sensor_api').split(',')[11].split('=')[1]}}
