# Energy monitors (TP-Link HS110)
- platform: template
  sensors:
    energy_monitor_1_total_consumption_kwh:
      value_template: '{{ states("sensor.energy_monitor_1_total_consumption") | float | round(0) }}'
      unit_of_measurement: kWh
    energy_monitor_2_total_consumption_kwh:
      value_template: '{{ states("sensor.energy_monitor_2_total_consumption") | float | round(0) }}'
      unit_of_measurement: kWh
    energy_monitor_3_total_consumption_kwh:
      value_template: '{{ states("sensor.energy_monitor_3_total_consumption") | float | round(0) }}'
      unit_of_measurement: kWh
