# Matrix panel
- platform: template
  sensors:
    matrix_temperature_outside:
      value_template: "{{ states(\"sensor.temperature_lowest_buiten\") | round(1, default=0) }}"
    matrix_temperature_inside:
      value_template: "{{ state_attr(\"climate.family_room\", \"current_temperature\") }}"
    matrix_inverter_outputpower:
      value_template: "{{ (state_attr(\"sensor.inverter_goodwe\", \"outputpower\") | float(default=0) / 1000) | round(1) }}"
    matrix_inverter_daytotal:
      value_template: "{{ states(\"sensor.daily_generation\") | round(0, default=0) }}"
    matrix_usage_dayenery:
      value_template: >
        {% if states("sensor.daily_energy") | float(default=0) <= -10 %}
          {% set decimals = 0 %}
        {% else %}
          {% set decimals = 1 %}
        {% endif %}
        {{ states("sensor.daily_energy") | round(decimals, default=0) }}
    matrix_usage_daygas:
      value_template: "{{ states(\"sensor.daily_gas\") | round(1, default=0) }}"
