# Hue sensors (Philips Hue RWL021, Philips Hue SML001, Philips Hue SML002)
- platform: min_max
  name: temperature_lowest_huiskamer
  type: min
  entity_ids:
    - sensor.motion_sensor_huiskamer_1_temperature
    - sensor.motion_sensor_huiskamer_2_temperature
- platform: min_max
  name: light_lowest_huiskamer
  type: min
  entity_ids:
    - sensor.motion_sensor_huiskamer_1_light
    - sensor.motion_sensor_huiskamer_2_light
- platform: min_max
  name: temperature_lowest_buiten
  type: min
  entity_ids:
    - sensor.motion_sensor_tuin_1_temperature
    - sensor.motion_sensor_tuin_2_temperature
    - sensor.motion_sensor_parkeerplaats_temperature
- platform: min_max
  name: light_lowest_buiten
  type: min
  entity_ids:
    - sensor.motion_sensor_tuin_1_light
    - sensor.motion_sensor_tuin_2_light
    - sensor.motion_sensor_parkeerplaats_light
- platform: template
  sensors:
    temperature_toilet:
      friendly_name: "Toilet Temperature"
      unit_of_measurement: '째C'
      value_template: "{{ (states('sensor.motion_sensor_toilet_temperature') | float) | round(1) }}"
    light_toilet:
      friendly_name: "Toilet Light Level"
      unit_of_measurement: 'lx'
      value_template: "{{ (states('sensor.motion_sensor_toilet_light') | float) | round(0) }}"
    temperature_huiskamer:
      friendly_name: "Huiskamer Temperature"
      unit_of_measurement: '째C'
      value_template: "{{ (states('sensor.temperature_lowest_huiskamer') | float) | round(1) }}"
    light_huiskamer:
      friendly_name: "Huiskamer Light Level"
      unit_of_measurement: 'lx'
      value_template: "{{ (states('sensor.light_lowest_huiskamer') | float) | round(0) }}"
    temperature_slaapkamer:
      friendly_name: "Slaapkamer Temperature"
      unit_of_measurement: '째C'
      value_template: "{{ (states('sensor.motion_sensor_slaapkamer_temperature') | float) | round(1) }}"
    light_slaapkamer:
      friendly_name: "Slaapkamer Light Level"
      unit_of_measurement: 'lx'
      value_template: "{{ (states('sensor.motion_sensor_slaapkamer_light') | float) | round(0) }}"
    temperature_buiten:
      friendly_name: "Buiten Temperature"
      unit_of_measurement: '째C'
      value_template: "{{ (states('sensor.temperature_lowest_buiten') | float) | round(1) }}"
    light_buiten:
      friendly_name: "Buiten Light Level"
      unit_of_measurement: 'lx'
      value_template: "{{ (states('sensor.light_lowest_buiten') | float) | round(0) }}"
