# Hue sensors (Philips Hue SML001, Philips Hue SML002)
- platform: min_max
  name: temperature_lowest_huiskamer
  type: min
  entity_ids:
    - sensor.huiskamer_motion_sensor_1_temperature
    - sensor.huiskamer_motion_sensor_2_temperature
- platform: min_max
  name: light_lowest_huiskamer
  type: min
  entity_ids:
    - sensor.huiskamer_motion_sensor_1_light_level
    - sensor.huiskamer_motion_sensor_2_light_level
- platform: min_max
  name: temperature_lowest_buiten
  type: min
  entity_ids:
    - sensor.tuin_motion_sensor_1_temperature
    - sensor.tuin_motion_sensor_2_temperature
    - sensor.parkeerplaats_motion_sensor_temperature
- platform: min_max
  name: light_lowest_buiten
  type: min
  entity_ids:
    - sensor.tuin_motion_sensor_1_light_level
    - sensor.tuin_motion_sensor_2_light_level
    - sensor.parkeerplaats_motion_sensor_light_level
- platform: template
  sensors:
    temperature_toilet:
      friendly_name: Toilet Temperature
      unit_of_measurement: 째C
      value_template: "{{ (states(\"sensor.toilet_motion_sensor_temperature\") | float(default=0)) | round(1) }}"
    light_toilet:
      friendly_name: Toilet Light Level
      unit_of_measurement: lx
      value_template: "{{ (states(\"sensor.toilet_motion_sensor_light_level\") | float(default=0)) | round(0) }}"
    temperature_huiskamer:
      friendly_name: Huiskamer Temperature
      unit_of_measurement: 째C
      value_template: "{{ (states(\"sensor.temperature_lowest_huiskamer\") | float(default=0)) | round(1) }}"
    light_huiskamer:
      friendly_name: Huiskamer Light Level
      unit_of_measurement: lx
      value_template: "{{ (states(\"sensor.light_lowest_huiskamer\") | float(default=0)) | round(0) }}"
    temperature_slaapkamer:
      friendly_name: Slaapkamer Temperature
      unit_of_measurement: 째C
      value_template: "{{ (states(\"sensor.slaapkamer_motion_sensor_temperature\") | float(default=0)) | round(1) }}"
    light_slaapkamer:
      friendly_name: Slaapkamer Light Level
      unit_of_measurement: lx
      value_template: "{{ (states(\"sensor.slaapkamer_motion_sensor_light_level\") | float(default=0)) | round(0) }}"
    temperature_buiten:
      friendly_name: Buiten Temperature
      unit_of_measurement: 째C
      value_template: "{{ (states(\"sensor.temperature_lowest_buiten\") | float(default=0)) | round(1) }}"
    light_buiten:
      friendly_name: Buiten Light Level
      unit_of_measurement: lx
      value_template: "{{ (states(\"sensor.light_lowest_buiten\") | float(default=0)) | round(0) }}"
