# Motion sensors (Philips Hue SML001, Philips Hue SML002)
- platform: min_max
  name: temperature_lowest_huiskamer
  type: min
  entity_ids:
    - sensor.motion_sensor_huiskamer_1_temperature
    - sensor.motion_sensor_huiskamer_2_temperature
- platform: min_max
  name: light_lowest_huiskamer
  type: min
  entity_ids:
    - sensor.motion_sensor_huiskamer_1_light
    - sensor.motion_sensor_huiskamer_2_light
- platform: min_max
  name: temperature_lowest_buiten
  type: min
  entity_ids:
    - sensor.motion_sensor_tuin_1_temperature
    - sensor.motion_sensor_tuin_2_temperature
    - sensor.motion_sensor_parkeerplaats_temperature
- platform: min_max
  name: light_lowest_buiten
  type: min
  entity_ids:
    - sensor.motion_sensor_tuin_1_light
    - sensor.motion_sensor_tuin_2_light
    - sensor.motion_sensor_parkeerplaats_light
- platform: template
  sensors:
    temperature_huiskamer:
      friendly_name: "Huiskamer Temperature"
      unit_of_measurement: '°C'
      value_template: "{{ (states('sensor.temperature_lowest_huiskamer') | float) | round(1) }}"
    light_huiskamer:
      friendly_name: "Huiskamer Light Level"
      unit_of_measurement: 'lx'
      value_template: "{{ (states('sensor.light_lowest_huiskamer') | float) | round(0) }}"
    temperature_buiten:
      friendly_name: "Buiten Temperature"
      unit_of_measurement: '°C'
      value_template: "{{ (states('sensor.temperature_lowest_buiten') | float) | round(1) }}"
    light_buiten:
      friendly_name: "Buiten Light Level"
      unit_of_measurement: 'lx'
      value_template: "{{ (states('sensor.light_lowest_buiten') | float) | round(0) }}"
- platform: rest
  name: motion_sensor_api
  resource: !secret api_hue_bridge
  verify_ssl: false
  scan_interval: 1
  value_template: >
    11={{ value_json["11"]["state"]["presence"] }},
    21={{value_json["14"]["state"]["presence"]}},
    14={{value_json["21"]["state"]["presence"]}},
    25={{value_json["25"]["state"]["presence"]}},
    33={{value_json["33"]["state"]["presence"]}}
