# Motion sensors (Philips Hue SML001, Philips Hue SML002)
- platform: min_max
  name: huiskamer_temperature_lowest
  type: min
  entity_ids:
    - sensor.hue_motion_sensor_1_temperature
    - sensor.hue_motion_sensor_2_temperature
- platform: min_max
  name: huiskamer_light_level_lowest
  type: min
  entity_ids:
    - sensor.hue_motion_sensor_1_light_level
    - sensor.hue_motion_sensor_2_light_level
- platform: min_max
  name: buiten_temperature_lowest
  type: min
  entity_ids:
    - sensor.hue_outdoor_motion_sensor_1_temperature
    - sensor.hue_outdoor_motion_sensor_2_temperature
- platform: min_max
  name: buiten_light_level_lowest
  type: min
  entity_ids:
    - sensor.hue_outdoor_motion_sensor_1_light_level
    - sensor.hue_outdoor_motion_sensor_2_light_level
- platform: template
  sensors:
    huiskamer_temperature:
      friendly_name: "Huiskamer Temperature"
      unit_of_measurement: '°C'
      value_template: "{{ (states('sensor.huiskamer_temperature_lowest') | float) | round(1) }}"
    huiskamer_light_level:
      friendly_name: "Huiskamer Light Level"
      unit_of_measurement: 'lx'
      value_template: "{{ (states('sensor.huiskamer_light_level_lowest') | float) | round(0) }}"
    buiten_temperature:
      friendly_name: "Buiten Temperature"
      unit_of_measurement: '°C'
      value_template: "{{ (states('sensor.buiten_temperature_lowest') | float) | round(1) }}"
    buiten_light_level:
      friendly_name: "Buiten Light Level"
      unit_of_measurement: 'lx'
      value_template: "{{ (states('sensor.buiten_light_level_lowest') | float) | round(0) }}"
