# Hue sensors (Philips Hue SML001, Philips Hue SML002)
- platform: min_max
  name: temperature_lowest_huiskamer
  type: min
  entity_ids:
    - sensor.huiskamer_motion_sensor_1_temperature
    - sensor.huiskamer_motion_sensor_2_temperature
- platform: min_max
  name: light_lowest_huiskamer
  type: min
  entity_ids:
    - sensor.huiskamer_motion_sensor_1_light_level
    - sensor.huiskamer_motion_sensor_2_light_level
- platform: min_max
  name: temperature_lowest_buiten
  type: min
  entity_ids:
    - sensor.tuin_motion_sensor_1_temperature
    - sensor.tuin_motion_sensor_2_temperature
    - sensor.parkeerplaats_motion_sensor_temperature
- platform: min_max
  name: light_lowest_buiten
  type: min
  entity_ids:
    - sensor.tuin_motion_sensor_1_light_level
    - sensor.tuin_motion_sensor_2_light_level
    - sensor.parkeerplaats_motion_sensor_light_level
