# Remote sensors (Philips Hue RWL021)
- platform: template
  sensors:
    # Sensor 2
    remote_1_button_update_api:
      value_template: >-
        {{ states('sensor.hue_sensor_api').split(',')[0].split('=')[1]}}
    remote_1_button_state_api:
      value_template: >-
        {{ states('sensor.hue_sensor_api').split(',')[1].split('=')[1]}}
    # Sensor 42
    remote_2_button_update_api:
      value_template: >-
        {{ states('sensor.hue_sensor_api').split(',')[8].split('=')[1]}}
    remote_2_button_state_api:
      value_template: >-
        {{ states('sensor.hue_sensor_api').split(',')[9].split('=')[1]}}
