# Solar inverter (GoodWe GW2500-XS)
- platform: sems
  username: !secret sems_username
  password: !secret sems_password
  station_id : !secret sems_station_id
  scan_interval: 60
- platform: template
  sensors:
    sems_portal_status:
      value_template: '{% if is_state("sensor.sems_portal", "1") %}Online{% else %}Offline{% endif %}'
    sems_portal_capacity:
      value_template: '{{ states.sensor.sems_portal.attributes.capacity | float }}'
      unit_of_measurement: 'kW'
    sems_portal_outputpower:
      value_template: '{{ states.sensor.sems_portal.attributes.outputpower | float / 1000 }}'
      unit_of_measurement: 'kW'
    sems_portal_temperature:
      value_template: '{{ states.sensor.sems_portal.attributes.tempperature }}'
      unit_of_measurement: "°C"
    sems_portal_hour_total:
      value_template: '{{ states.sensor.sems_portal.attributes.hour_total | round(0) }} uur'
    sems_portal_eday:
      value_template: '{{ states.sensor.sems_portal.attributes.eday | float }}'
      unit_of_measurement: 'kWh'
    sems_portal_etotal:
      value_template: '{{ states.sensor.sems_portal.attributes.etotal | float }}'
      unit_of_measurement: 'kWh'
