- platform: systemmonitor
  resources:
    - type: processor_use
    - type: memory_use_percent
    - type: memory_use
    - type: memory_free
    - type: disk_use_percent
    - type: disk_use
    - type: disk_free
    - type: throughput_network_in
      arg: enp0s2
    - type: throughput_network_out
      arg: enp0s2
    - type: last_boot
