# System monitoring
- platform: command_line
  name: Processor temperature
  command: cat /sys/class/thermal/thermal_zone0/temp
  unit_of_measurement: °C
  scan_interval: 30
  value_template: "{{ value | multiply(0.001) | round(1) }}"
- platform: command_line
  name: RPI version
  command: cat /sys/firmware/devicetree/base/model
  value_template: "{{ value.split(\"Model\")[0] }}"
- platform: command_line
  name: RPI memory
  command: cat /proc/meminfo | grep MemTotal
  unit_of_measurement: MB
  value_template: "{{ value.split()[1] | multiply(0.001) | round(0) }}"
- platform: systemmonitor
  resources:
    - type: processor_use
    - type: memory_use_percent
    - type: disk_use_percent
      arg: /
    - type: throughput_network_in
      arg: eth0
    - type: throughput_network_out
      arg: eth0
    - type: last_boot
- platform: uptime
- platform: filesize
  file_paths: !secret file_paths
