# Utility meter sensors
- platform: template
  sensors:
    daily_gas:
      friendly_name: Daily Gas
      unit_of_measurement: m3
      value_template: "{{ states('sensor.daily_gas_consumption') }}"
    daily_energy_consumption:
      friendly_name: Daily Energy Consumption
      unit_of_measurement: kWh
      value_template: "{{ (states('sensor.daily_energy_consumption_offpeak') | float + states('sensor.daily_energy_consumption_peak') | float) | round(3) }}"
    daily_energy_production:
      friendly_name: Daily Energy Production
      unit_of_measurement: kWh
      value_template: "{{ (states('sensor.daily_energy_production_offpeak') | float + states('sensor.daily_energy_production_peak') | float) | round(3)  }}"
    daily_energy:
      friendly_name: Daily Energy
      unit_of_measurement: kWh
      value_template: "{{ (states('sensor.daily_energy_consumption') | float - states('sensor.daily_energy_production') | float) | round(3) }}"
    monthly_gas:
      friendly_name: Monthly Gas
      unit_of_measurement: m3
      value_template: "{{ states('sensor.monthly_gas_consumption') | float | round(0) }}"
    monthly_energy_consumption:
      friendly_name: Monthly Energy Consumption
      unit_of_measurement: kWh
      value_template: "{{ (states('sensor.monthly_energy_consumption_offpeak') | float + states('sensor.monthly_energy_consumption_peak') | float) | round(0) }}"
    monthly_energy_production:
      friendly_name: Monthly Energy Production
      unit_of_measurement: kWh
      value_template: "{{ (states('sensor.monthly_energy_production_offpeak') | float + states('sensor.monthly_energy_production_peak') | float) | round(0) }}"
    monthly_energy:
      friendly_name: Monthly Energy
      unit_of_measurement: kWh
      value_template: "{{ (states('sensor.monthly_energy_consumption') | float - states('sensor.monthly_energy_production') | float) | round(0) }}"
    total_gas:
      friendly_name: Total Gas
      unit_of_measurement: m3
      value_template: "{{ states('sensor.gas_consumption') | float | round(0) }}"
    total_energy_consumption:
      friendly_name: Total Energy Consumption
      unit_of_measurement: kWh
      value_template: "{{ (states('sensor.energy_consumption_tarif_1') | float + states('sensor.energy_consumption_tarif_2') | float) | round(0) }}"
    total_energy_production:
      friendly_name: Total Energy Production
      unit_of_measurement: kWh
      value_template: "{{ (states('sensor.energy_production_tarif_1') | float + states('sensor.energy_production_tarif_2') | float) | round(0) }}"
    total_energy:
      friendly_name: Total Energy
      unit_of_measurement: kWh
      value_template: "{{ (states('sensor.total_energy_consumption') | float - states('sensor.total_energy_production') | float) | round(0) }}"
