# Utility meter sensors
- platform: derivative
  name: Hourly water consumption
  source: sensor.water_consumption_total
  round: 0
  unit_time: h
  unit: L/h
  time_window: 00:05:00
- platform: derivative
  name: Hourly gas
  source: sensor.gas_consumption
  unit_time: h
  unit: m³/h
  time_window: 00:05:00
