- alias: Motion huiskamer detected
  trigger:
    platform: state
    entity_id: group.motion_huiskamer
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.huiskamer
        state: 'off'
      - condition: or
        conditions:
          - condition: numeric_state
            entity_id: sensor.motion_sensor_huiskamer_1_light
            below: 2
          - condition: numeric_state
            entity_id: sensor.motion_sensor_huiskamer_2_light
            below: 2
  action:
    - service: script.hue_scene_huiskamer_motion
- alias: Motion huiskamer undetected
  trigger:
    platform: state
    entity_id: binary_sensor.presence_huiskamer
    to: 'off'
    for:
      minutes: 2
  condition:
    condition: state
    entity_id: light.huiskamer
    state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.huiskamer
