- alias: Motion tuin detected
  trigger:
    platform: state
    entity_id: group.motion_tuin
    to: 'on'
  condition:
    condition: and
    conditions:    
      - condition: state
        entity_id: light.tuin
        state: 'off'
      - condition: or
        conditions:
          - condition: numeric_state
            entity_id: sensor.motion_sensor_tuin_1_light
            below: 5
          - condition: numeric_state
            entity_id: sensor.motion_sensor_tuin_2_light
            below: 5
  action:
    - service: script.hue_scene_tuin_motion
    - service: input_text.set_value
      data:
        entity_id: input_text.motion_automation_tuin_is_triggered
        value: 'true'
- alias: Motion tuin undetected
  trigger:
    platform: state
    entity_id: group.motion_tuin
    to: 'off'
    for:
      minutes: 2
  condition:
    condition: state
    entity_id: input_text.motion_automation_tuin_is_triggered
    state: 'true'
  action:
    - service: light.turn_off
      entity_id: light.tuin
    - service: input_text.set_value
      data:
        entity_id: input_text.motion_automation_tuin_is_triggered
        value: 'false'
