- alias: Motion huiskamer detected
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.hue_motion_sensor_1_motion_api
        - binary_sensor.hue_motion_sensor_2_motion_api
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.huiskamer
        state: 'off'
      - condition: or
        conditions:
          - condition: numeric_state
            entity_id: sensor.hue_motion_sensor_1_light_level
            below: 2
          - condition: numeric_state
            entity_id: sensor.hue_motion_sensor_2_light_level
            below: 2
  action:
    - service: script.hue_scene_huiskamer_motion
