- alias: Motion parkeerplaats detected
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_parkeerplaats_motion_api
    to: 'on'
  condition:
    condition: and
    conditions:    
      - condition: state
        entity_id: light.parkeerplaats
        state: 'off'
      - condition: numeric_state
        entity_id: sensor.motion_sensor_parkeerplaats_light
        below: 5
  action:
    - service: script.hue_scene_parkeerplaats_motion
    - service: input_text.set_value
      data:
        entity_id: input_text.motion_automation_parkeerplaats_is_triggered
        value: 'true'
- alias: Motion parkeerplaats undetected
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_parkeerplaats_motion_api
    to: 'off'
    for:
      minutes: 2
  condition:
    condition: state
    entity_id: input_text.motion_automation_parkeerplaats_is_triggered
    state: 'true'
  action:
    - service: light.turn_off
      entity_id: light.parkeerplaats
    - service: input_text.set_value
      data:
        entity_id: input_text.motion_automation_parkeerplaats_is_triggered
        value: 'false'
