alias: Motion huiskamer detected
trigger:
  - platform: state
    entity_id:
      - binary_sensor.hue_motion_sensor_1_motion
      - binary_sensor.hue_motion_sensor_2_motion
    to: 'on'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: light.huiskamer
      state: 'off'
    - condition: or
      conditions:
        - condition: numeric_state
          entity_id: sensor.hue_motion_sensor_1_light_level
          below: 2
        - condition: numeric_state
          entity_id: sensor.hue_motion_sensor_2_light_level
          below: 2
action:
  - service: homeassistant.turn_on
    data_template:
      entity_id: light.keuken
      brightness: 102
      color_temp: 400
  - service: homeassistant.turn_on
    data_template:
      entity_id: light.speelhoek
      brightness: 102
      color_temp: 400
  - service: homeassistant.turn_on
    data_template:
      entity_id: light.aanbouw
      brightness: 102
      color_temp: 400
