alias: Motion tuin undetected
trigger:
  platform: state
  entity_id: binary_sensor.hue_outdoor_motion_sensor_1_motion
  to: 'off'
  for:
    minutes: 2
condition:
  condition: state
  entity_id: input_text.tuin_motion_automation_is_triggered
  state: 'true'
action:
  - service: homeassistant.turn_off
    entity_id:
      - light.achterdeur
      - light.tuin
  - service: input_text.set_value
    data_template:
      entity_id: input_text.tuin_motion_automation_is_triggered
      value: 'false'
