alias: Motion outdoor detected
trigger:
  platform: state
  entity_id: binary_sensor.hue_outdoor_motion_sensor_1_motion
  to: 'on'
condition:
  - condition: state
    entity_id: light.tuin
    state: 'off'
  - condition: numeric_state
    entity_id: sensor.outdoor_motion_sensor_light_level
    below: 5
action:
  - service: homeassistant.turn_on
    data:
      brightness: 255
      entity_id:
        - light.achterdeur
        - light.tuin
  - service: input_text.set_value
    data_template:
      entity_id: input_text.outdoor_motion_automation_is_triggered
      value: 'true'
