alias: Motion indoor detected
trigger:
  platform: state
  entity_id: binary_sensor.huiskamersensor_motion
  to: 'on'
condition:
  - condition: state
    entity_id: light.huiskamer
    state: 'off'
  - condition: numeric_state
    entity_id: sensor.indoor_motion_sensor_light_level
    below: 2
action:
  service: homeassistant.turn_on
  data:
    brightness: 102
    color_temp: 400
    entity_id:
      - light.keuken
      - light.speelhoek
      - light.aanbouw
