- alias: Remote kerstboom pressed
  mode: restart
  trigger: 
    platform: state 
    entity_id: sensor.remote_2_button_update_api 
  action: 
    - choose:
      - conditions:
        - condition: and
          conditions:
            - condition: state
              entity_id: switch.753802832462ab3c0e52
              state: 'off'
            - condition: state
              entity_id: sensor.remote_2_button_state_api
              state:
                - "1000"
                - "1001"
                - "1002"
                - "1003"
                - "2000"
                - "2001"
                - "2002"
                - "2003"
        sequence:
          service: switch.turn_on
          entity_id: switch.753802832462ab3c0e52
      - conditions:
        - condition: and
          conditions:
            - condition: state
              entity_id: switch.753802832462ab3c0e52
              state: 'on'
            - condition: state
              entity_id: sensor.remote_2_button_state_api
              state:
                - "3000"
                - "3001"
                - "3002"
                - "3003"
                - "4000"
                - "4001"
                - "4002"
                - "4003"
        sequence:
          service: switch.turn_off
          entity_id: switch.753802832462ab3c0e52
