- alias: Remote huiskamer pressed
  mode: restart
  trigger: 
    platform: state 
    entity_id: sensor.remote_1_button_update_api 
  action: 
    - choose:
      - conditions:
          - condition: state
            entity_id: sensor.remote_1_button_state_api
            state: "1001"
        sequence:
          - service: script.scene_huiskamer_tvkijken
      - conditions:
          - condition: state
            entity_id: sensor.remote_1_button_state_api
            state: 
              - "1000"
              - "1002"
        sequence:
          - delay:
              seconds: 1
          - choose:
            - conditions:
                - condition: state
                  entity_id: input_text.scene_huiskamer_last_triggered
                  state: "scene_huiskamer_spelen"
              sequence:
                - service: script.scene_huiskamer_overdag
            - conditions:
                - condition: state
                  entity_id: input_text.scene_huiskamer_last_triggered
                  state: "scene_huiskamer_overdag"
              sequence:
                - service: script.scene_huiskamer_avond
            - conditions:
                - condition: state
                  entity_id: input_text.scene_huiskamer_last_triggered
                  state: "scene_huiskamer_avond"
              sequence:
                - service: script.scene_huiskamer_eten
            - conditions:
                - condition: state
                  entity_id: input_text.scene_huiskamer_last_triggered
                  state: "scene_huiskamer_eten"
              sequence:
                - service: script.scene_huiskamer_koken
            - conditions:
                - condition: state
                  entity_id: input_text.scene_huiskamer_last_triggered
                  state: "scene_huiskamer_koken"
              sequence:
                - service: script.scene_huiskamer_tvkijken
            - conditions:
                - condition: state
                  entity_id: input_text.scene_huiskamer_last_triggered
                  state: "scene_huiskamer_tvkijken"
              sequence:
                - service: script.scene_huiskamer_spelen
      - conditions:
          - condition: state
            entity_id: sensor.remote_1_button_state_api
            state: 
              - "2000"
              - "2001"
              - "2002"
        sequence:
          - service: script.scene_huiskamer_brighter
      - conditions:
          - condition: state
            entity_id: sensor.remote_1_button_state_api
            state: 
              - "3000"
              - "3001"
              - "3002"
        sequence:
          - service: script.scene_huiskamer_dimmer
      - conditions:
          - condition: state
            entity_id: sensor.remote_1_button_state_api
            state: 
              - "4000"
              - "4001"
              - "4002"
        sequence:
          - service: script.scene_huiskamer_off
